# Generated by promptkit -- do not edit. Regenerate with: promptkit update

CARGO ?= cargo
PROFILE ?= release
TARGET_DIR ?= target

VERSION   = $(shell git describe --tags --always --dirty 2>/dev/null || echo "dev")
GIT_COMMIT = $(shell git rev-parse --short HEAD 2>/dev/null || echo "none")

all: build

# Build all binaries
.PHONY: build
build:
	$(CARGO) build --profile $(PROFILE) --bin plaude-cli

# Show help
.PHONY: help
help:
	@echo "Available targets:"
	@echo "  build            - Build all binaries (release)"
	@echo "  install          - Install binaries to ~/.cargo/bin"
	@echo "  test             - Run all tests"
	@echo "  testv            - Run all tests (verbose)"
	@echo "  lint             - Run clippy, fmt check, and audit"
	@echo "  fmt              - Format code"
	@echo "  audit            - Run cargo audit"
	@echo "  clean            - Clean build artifacts"
	@echo "  bench            - Run benchmarks"

# Generate man pages from --help output (requires help2man)
.PHONY: man
man: build
	@mkdir -p $(TARGET_DIR)/man
	@if command -v help2man >/dev/null 2>&1; then \
		help2man --no-info --no-discard-stderr \
			$(TARGET_DIR)/$(PROFILE)/plaude-cli \
			-o $(TARGET_DIR)/man/plaude-cli.1; \
		echo "Man page generated at $(TARGET_DIR)/man/plaude-cli.1"; \
	else \
		echo "help2man not found — skipping man page generation"; \
	fi

# Install binaries (and man pages if generated)
.PHONY: install
install: build
	$(CARGO) install --path crates/plaude-cli --bin plaude-cli
	@if [ -f $(TARGET_DIR)/man/plaude-cli.1 ]; then \
		mkdir -p $(HOME)/.local/share/man/man1; \
		cp $(TARGET_DIR)/man/plaude-cli.1 $(HOME)/.local/share/man/man1/; \
		echo "Man page installed to $(HOME)/.local/share/man/man1/"; \
	fi

# Run all tests
.PHONY: test
test:
	$(CARGO) test --all-targets --all-features

# Run all tests with verbose output
.PHONY: testv
testv:
	$(CARGO) test --all-targets --all-features -- --nocapture

# Run benchmarks
.PHONY: bench
bench:
	$(CARGO) bench --all-features

# Lint: clippy + fmt check + audit
.PHONY: lint
lint:
	@echo "Running clippy..."
	$(CARGO) clippy --all-targets --all-features -- -D warnings
	@echo "Checking formatting..."
	$(CARGO) fmt --all --check
	@echo "Running cargo audit..."
	$(CARGO) audit || true
	@echo "Linting complete"

# Format code
.PHONY: fmt
fmt:
	$(CARGO) fmt --all

# Security audit
.PHONY: audit
audit:
	$(CARGO) audit

# Clean build artifacts
.PHONY: clean
clean:
	$(CARGO) clean
